### ISSUE TITLE
Add fetch source from DANCERUSH STARDOM

### ISSUE THREAD

**Issue by NerovaRiuzGX** [zetaraku/arcade-songs#15]
Hi, Nerova here.

As a part of the DRS community, we've struggled to get songs sorted in the past few years.
All the existing methods, including wiki, bots, and spreadsheets, are hard to maintain or will eventually go down at any moment.

Is it possible to have DRS included in both arcade-songs and arcade-songs-fetch?

**Comment by zetaraku** [comment]
Hello Nerova!

Sorry for the late reply. I just saw this issue today.

Since all the data required are available for free on the official site, adding DRS into arcade-songs would be easy.
I'll start writing the script to get the data.

Thank you for the suggestion!

**Comment by zetaraku** [comment]
Scripts pushed to arcade-songs-fetch repo.
